GET http://localhost:5000/api/locations

###

POST http://localhost:5000/api/locations
Content-Type: application/json

{
    "title": "Ohio",
    "country": "United States Of America"
}

###

PUT http://localhost:5000/api/locations
Content-Type: application/json

{
    "id": 1,
    "title": "Los Angeles",
    "country": "United States Of America"
}

###

DELETE http://localhost:5000/api/locations/1