GET http://localhost:5000/api/studios

###

POST http://localhost:5000/api/studios
Content-Type: application/json

{
    "title": "Warner Bros.",
    "found_year": "1923-04-04",
    "location": "Ohio"
}

###

GET http://localhost:5000/api/studios/2

###
PUT http://localhost:5000/api/studios
Content-Type: application/json

{
    "id": 1,
    "title": "Warner Bros.",
    "found_year": "1923-04-04",
    "location": "Ohio"
}

###

DELETE http://localhost:5000/api/studios/1

###

GET http://localhost:5000/api/studios/selectStudios